/// Built-in default options as a JSON-like map (can be persisted/overridden).
/// Canonicals map to themselves by default. Adjust values if you want alias→canonical.
const Map<String, dynamic> kReceiptDefaultOptions = {
  'storeNames': {
    'Aldi': 'Aldi',
    'Rewe': 'Rewe',
    'Edeka': 'Edeka',
    'Penny': 'Penny',
    'Lidl': 'Lidl',
    'Kaufland': 'Kaufland',
    'Netto': 'Netto',
    'Akzenta': 'Akzenta',
  },
  'totalLabels': {
    'Zu zahlen': 'Zu zahlen',
    'Gesamt': 'Gesamt',
    'Summe': 'Summe',
    'Total': 'Total',
  },
  'ignoreKeywords': [
    'E-Bon',
    'Coupon',
    'Eingabe',
    'Posten',
    'Subtotal',
    'Stk x',
    'kg x',
  ],
  'stopKeywords': ['Geg.', 'Rückgeld', 'Bar', 'Change'],
  'foodKeywords': ['B', '2', 'BW'],
  'nonFoodKeywords': ['A', '1', 'AW'],
  'discountKeywords': ['Rabatt', 'Coupon', 'Discount'],
  'depositKeywords': ['Leerg.', 'Leergut', 'Einweg', 'Pfand', 'Deposit'],
  'tuning': {
    'optimizerTotalTolerance': 0.009,
    'optimizerVerticalTolerance': 50,
    'optimizerLoopThreshold': 10,
    'optimizerMaxCacheSize': 15,
    'optimizerConfidenceThreshold': 80,
    'optimizerStabilityThreshold': 50,
    'optimizerEwmaAlpha': 0.3,
    'optimizerAboveCountDecayThreshold': 50,
    'optimizerVariantMinSim': 0.85,
    'optimizerMinProductSimToMerge': 0.5,
  },
};
